import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "ConnectaSys",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.ico', // Substitua pelo nome do seu arquivo
    // Você pode adicionar outros tamanhos/formatos
    apple: '/apple-icon.png',
    other: {
      rel: 'icon',
      url: '/icon.png',
    },
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}